mongoimport -d mall_jzb -c province --file server/db/mongo/citydata/province.json --jsonArray
mongoimport -d mall_jzb -c city --file server/db/mongo/citydata/city.json --jsonArray
mongoimport -d mall_jzb -c area --file server/db/mongo/citydata/area.json --jsonArray